### PR TITLE
Rabi-oscillation detuning scan with a floated pulse area. 

### PR DESCRIPTION
**Pull request by pathfinder49**
As requested [here](https://github.com/OxfordIonTrapGroup/oitg/issues/9).

Good fitting required modification of FitBase to automatically find the parameter scale.

### CODE REVIEW

**Comment by dnadlinger** [comment]
Thanks, I'll give it a go.

**Comment by pathfinder49** [comment]
Hm... the test case can't seem to load data from a file. will revert back to previous version.

**Comment by pathfinder49** [comment]
If you're happy with this I'll merge.

**Comment by dnadlinger** [comment]
I don't find the named `detuned_pulse_area` very descriptive at all – physically, the fit corresponds to a detuning scan of a square pulse over a two-level transition, or mathematically a generalised sinc^2 shape. (If the pulse is not square, then the frequency response – the Fourier transform of the aperture – won't be of a sinc^2 type.)

Actually, from a (my) user's perspective, this is exactly the same as sinc_2 with one more parameter floated, and I don't expect to use bare sinc_2 much, as for already close-to-calibrated pulses, I'd use a two-point servo instead. Perhaps merging this into sinc_2 implementation for both cases would be worth it?

**Comment by pathfinder49** [comment]
I agree this implementation is more likely to be used than sinc^2. However, sinc^2 fitting can make better initial guesses.

I agree `detuned_square_pulse` would be a better name.

**Comment by dnadlinger** [comment]
Test failure was unrelated; the test_sinusoid randomised tests fail too frequently (I've increased the acceptable delta).

**Comment by pathfinder49** [comment]
I'm seeing degraded fit performance in some instances using `method='trf'` and `x_scale='jac'`. Are you sure this is not a symtom of the PR?

**Comment by dnadlinger** [comment]
Hmm, true, might be – I've seen a similar failure once before, though.

**Comment by pathfinder49** [comment]
> 
> 
> Hmm, true, might be – I've seen a similar failure once before, though.

**Comment by pathfinder49** [comment]
I've updated the x_scale to be inferred from the initial guess. This improves reliability with the old sinusoid test cases. However the detuned_pulse area tests now fail. I'll look into making the detuned pulse area finitialiser smarter.

**Comment by pathfinder49** [comment]
I'll merge once someone has reviewed the FitBase changes.

**Pull request merged**
